spring:
  profiles:
    active:
    - local
---
spring:
  profiles:
  - local
logging:
  level:
    root: info  

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${vcap.services.NPCloud-mysql.credentials.url}
    userName: ${vcap.services.NPCloud-mysql.credentials.username}
    password: ${vcap.services.NPCloud-mysql.credentials.password}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

